name: CI/CD Backend por Bastion

on:
  push:
    branches:
      - deploy

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código de GitHub
        uses: actions/checkout@v3

      - name: Despliegue en Red Privada usando Frontend como Puente
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }} # IP Pública del Front: 44.214.67.2
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }} # Llave devops.pem
          script: |
            # 1. Crear temporalmente la llave dentro del Frontend para el salto
            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_bastion.pem
            chmod 600 ~/.ssh/id_bastion.pem
            
            # 2. Conectarse al Backend usando SSH sobre IP privada y ejecutar los comandos internos
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_bastion.pem ec2-user@10.0.152.125 << 'EOF'
              # --- Comandos dentro de la EC2 Backend ---
              mkdir -p ~/backend-app && cd ~/backend-app
              
              # Limpieza total preventiva
              rm -rf *
              
              # Descargar el código de la rama deploy
              git clone -b deploy https://github.com/glenVon/Back_EVAL2.git .
              
              # Integración de la Capa de Datos (Data_Eval2) para la persistencia inicial
              mkdir -p init
              curl -s https://raw.githubusercontent.com/glenVon/Data_Eval2/main/01_creacion_base_datos.sql -o init/01_creacion_base_datos.sql
              
              # Orquestar contenedores (NodeJS + MySQL)
              docker compose down || true
              docker compose up -d --build
              
              # Mantener el almacenamiento de la EC2 optimizado
              docker image prune -f
            EOF
            
            # 3. Control de daños y seguridad: Eliminar la llave del Frontend de inmediato
            rm -f ~/.ssh/id_bastion.pem
