name: CI/CD Backend Innovatech

on:
  push:
    branches:
      - deploy

jobs:
  deploy-back:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v3

      - name: Desplegar en EC2 Backend vía SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }} # Nota: Usa la IP que configuraste para conectar al Back
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Crear carpeta y entrar
            mkdir -p ~/backend-app && cd ~/backend-app
            
            # Limpiar contenido anterior
            rm -rf *
            
            # Clonar la rama deploy del Backend
            git clone -b deploy https://github.com/glenVon/Back_EVAL2.git .
            
            # Configurar carpeta init para el script SQL de Data_Eval2 (Persistencia)
            mkdir -p init
            # Descargamos el script SQL directo desde tu repositorio de datos
            curl -s https://raw.githubusercontent.com/glenVon/Data_Eval2/main/01_creacion_base_datos.sql -o init/01_creacion_base_datos.sql
            
            # Levantar el stack completo (Node.js API + MySQL) con volumen persistente
            docker compose down || true
            docker compose up -d --build
            
            # Limpieza de imágenes en desuso
            docker image prune -f