name: CI/CD Backend - Deploy to Private EC2

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/back-eval2:latest

  deploy-to-private-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH Proxy to Private Server
      uses: appleboy/ssh-action@master
      with:
        host: '10.0.3.201'
        username: 'ec2-user'
        key: ${{ secrets.SSH_KEY }}
        proxy_host: '32.199.17.172'
        proxy_username: 'ec2-user'
        proxy_key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user/Back_EVAL2
          git fetch origin
          git checkout deploy || git checkout -b deploy origin/deploy
          git reset --hard origin/deploy
          
          # Liberar el puerto 3306 antes de levantar Docker
          sudo systemctl stop mysqld || true
          sudo systemctl stop mysql || true
          sudo docker rm -f mysql_db || true
          
          sudo docker compose pull
          sudo docker compose up -d --remove-orphans
